spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mariadb://${MARIADB_HOST}:${MARIADB_PORT}/${MARIADB_DATABASE}
    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false